pluginInfo:
  # This is default sample specification
  # Feel free to change it
  # Call flowpdk showdoc pluginspec to see the list of available fields and their description
  pluginName: 'EC-FlowUI-Bugs'
  version: '1.0.0'
  description: 'The plugin is made to help Flow UI team reproduce the bugs. It also contains time information of when the bug was found and fixed'
  author: 'none'
  supportUrl: 'none'
  category: 'Utilities'
  shell: 'ec-groovy'

# Plugin configuration description
configuration:
  # This is a shell used for checking connection
  shell: 'ec-groovy'
  # A script for checking connection will be generated
  checkConnection: 'true'
  # A set of fields will be added to process debug level in the configuration
  hasDebugLevel: true
  parameters:
  -
    name: config
    documentation: The name for the created configuration
    required: true
    type: entry
    label: Configuration Name
  -
    name: desc
    documentation: Description for the configuration
    required: false
    type: entry
    label: Description
  -
    name: endpoint
    documentation: Third-party endpoint to connect to.
    required: false
    type: entry
    label: Endpoint
  -
    name: credential
    documentation: A sample credential
    required: true
    type: credential
    label: Credential

procedures:
-
  name: 'CEV-21976'
  description: '03/06/19. FlowUI. CollectionValueRequired makes the parameter act as required.'
  hasConfig: false
  parameters:
  -
    name: applicationPath
    documentation: Path to the application
    required: true
    default: '/bin/sh'
    value: '/bin/sh'
    type: entry
    label: Application Path

  - name: applicationParameters
    htmlDocumentation: |
      Parameters to be passed to the app, specified as name-value pairs, with 1 pair per line. <br/>If not specified, the default variables for the definition will be used. <br/>Example: <br/>
      <b>system.debug=true</b> <br/>
      <b>BuildConfiguration=debug</b> <br/>
      <b>BuildPlatform=x64</b>
    required: 0
    collection: 1
    collectionName : 'Parameter name'
    collectionValue : 'Parameter value'
    collectionValueRequired : '1'
    collectionEntrySeparator : '\n'
    collectionValueSeparator : '='

-
  name: 'CEV-21977'
  description: '03/06/19. FlowUI. Empty Collection Entry results in separator passed to the the step as a value'
  hasConfig: false
  parameters:
    -
      name: applicationPath
      documentation: Path to the application
      required: true
      default: '/bin/sh'
      value: '/bin/sh'
      type: entry
      label: Application Path

    - name: applicationParameters
      htmlDocumentation: |
        Parameters to be passed to the app, specified as name-value pairs, with 1 pair per line. <br/>If not specified, the default variables for the definition will be used. <br/>Example: <br/>
        <b>system.debug=true</b> <br/>
        <b>BuildConfiguration=debug</b> <br/>
        <b>BuildPlatform=x64</b>
      collection: 1
      collectionName : 'Parameter name'
      collectionValue : 'Parameter value'
      collectionValueRequired : '0'
      collectionEntrySeparator : '\n'
      collectionValueSeparator : '='